[build]
  command = "npm run build"  # Ensure this matches your package.json scripts
  publish = "dist"  # Output directory for Vite

[[redirects]]
  from = "/api/*"
  to = "https://kmla-warehouse-backend.netlify.app/api/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200