[build]
  base = "backend/"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  format = "cjs"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
